version: "3.4"

services:
    cod-to-disk:
        image: 'ghcr.io/chemistry/api.crystallography.io/cod-to-disk:latest'
        restart: always
        volumes:
          - cod-data:/home/data
        networks:
          - net
        build:
            context: ./packages/cod-to-disk
            dockerfile: Dockerfile
        env_file:
          - ./.env

    cod-processor:
        image: 'ghcr.io/chemistry/api.crystallography.io/cod-processor:latest'
        restart: always
        volumes:
          - cod-data:/home/data
        networks:
          - net
        build:
            context: ./packages/cod-processor
            dockerfile: Dockerfile
        env_file:
          - ./.env

networks:
  net:
  traefik-public:
    external: true

volumes:
    cod-data:
